version: '3.8'
services:
  frontend:
    image: batuhanacet/frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      vplidenet:
        ipv4_address: "172.18.0.3"

  backend:
    image: batuhanacet/backend:latest
    build: ./backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - vpl:/usr/src/app/media
    networks:
      vplidenet:
        ipv4_address: "172.18.0.2"

  execution_server:
    image: batuhanacet/execserver:latest
    build: ./execution_server
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - vpl:/usr/src/app/media
    networks:
      vplidenet:
        ipv4_address: "172.18.0.4"

volumes:
  vpl:

networks:
  vplidenet:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
